### ISSUE TITLE
How to use not user provided db context?

### ISSUE THREAD

**Issue by artworkad** [sergezhigunov/Hangfire.EntityFrameworkCore#22]
Can you add more documentation on how this library is supposed to work? At first I expected it to expose the DbContext so that I can do the following:

```
Jobs = await _context.Jobs
  // Do more fluent stuff
  .ToListAsync(cancellationToken)
```

But I could not find any way to achieve that. I am interested in having access to the context, so that I can use IQueryable. I also tried my own DbContext, but was getting `SqlException: Invalid object name 'HangfireCounter'.`

**Comment by sergezhigunov** [comment]
To implement custom queries you should use [your own context](https://github.com/sergezhigunov/Hangfire.EntityFrameworkCore#using-your-own-dbcontext).
Then you can use entities like
```csharp
yourOwnContext.Set<HangfireJob>();
```
