### ISSUE TITLE
Is it possible to use it for finding Job using other columns than Id (e.g. Arguments)

### ISSUE THREAD

**Issue by stefan-ma22** [sergezhigunov/Hangfire.EntityFrameworkCore#24]
I am trying to check JOB status by in Hangfire its only possible via ID. I would like to use Arguments column e.g. whit WHERE Arguments LIKE.

**Comment by sergezhigunov** [comment]
Hi, @marhyno. I am planning to make entities and context public #23 in the 0.5.0 version. This will allow you to use the context and entities as you like including making custom queries.
